variable "name" {
  description = "The name of the application, used as a suffix for resources."
  type        = string
}

variable "slug" {
  description = "The slug for the application, used as a prefix for resources."
  type        = string
}

variable "deployment_domain" {
  description = "The deployment domain for the application. This must exist in Route 53. Leave blank to skip domain setup and use the default CloudFront domain."
  type        = string
}

variable "server_streaming" {
  description = "Whether to enable response streaming on the server function. Enables faster Time to First Byte for server-rendered pages."
  type        = bool
  default     = false
}

variable "acm_arn" {
  description = "The ARN of an existing ACM certificate to use for the CloudFront distribution."
  type        = string
}

variable "waf_arn" {
  description = "The ARN of the WAF to use for the CloudFront distribution."
  type        = string
  default     = null
}

variable "aws_region" {
  description = "The AWS region to deploy to."
  type        = string
}

variable "use_account_regional_buckets" {
  type        = bool
  description = "Whether S3 buckets should use account-regional namespace (BUCKET-ACCOUNTID-REGION-an) instead of global namespace. Account-regional is recommended to avoid naming conflicts."
  default     = true
}

variable "runtime_environment_variables" {
  description = "Environment variables configured on the OpenNext server function."
  type        = map(string)
  default     = {}
}

variable "runtime_iam_execution_policy_statements" {
  description = "Additional IAM policy statements to attach to the OpenNext server function execution role. This can be used to grant permissions for accessing other AWS resources from the server function."
  type = list(object({
    effect    = string
    actions   = list(string)
    resources = list(string)
  }))
  default = []
}

variable "image_optimization_iam_execution_policy_statements" {
  description = "Additional IAM policy statements to attach to the OpenNext image optimization function execution role. This can be used to grant permissions for accessing other AWS resources from the image optimization function."
  type = list(object({
    effect    = string
    actions   = list(string)
    resources = list(string)
  }))
  default = []
}

variable "hosted_zone_id" {
  type        = string
  description = "The Route 53 hosted zone ID."
  default     = null

  validation {
    condition     = !(var.hosted_zone_id != null && var.deployment_domain == "")
    error_message = "hosted_zone_id cannot be provided when deployment_domain is empty"
  }
}

variable "create_dns_records" {
  type        = bool
  description = "Whether to create Route 53 DNS records. Set to true when providing hosted_zone_id."
  default     = false

  validation {
    condition     = !(var.create_dns_records && var.hosted_zone_id == null)
    error_message = "create_dns_records cannot be true when hosted_zone_id is null"
  }
}

variable "opennext_build_path" {
  type        = string
  description = "The path to the OpenNext build output directory."
}

variable "warmer_function_enabled" {
  type        = bool
  description = "Whether to create a Lambda function to keep the OpenNext server warm. This can help reduce cold start times, but will incur additional cost."
  default     = true
}

variable "static_paths" {
  type        = list(string)
  description = "List of static paths to be cached by CloudFront. These should correspond to the static assets generated by OpenNext."
  default     = ["/llms.txt", "/llms-full.txt", "/.well-known/*"]
}

variable "enable_www_alias" {
  type        = bool
  description = "Whether to create an additional alias with the www prefix (e.g. www.example.com) and a corresponding Route 53 record if hosted_zone_id is provided."
  default     = true
}

variable "cdn_price_class" {
  type        = string
  description = "The CloudFront price class to use for the distribution. This determines the maximum price tier for serving content. Valid values are `PriceClass_100`, `PriceClass_200`, and `PriceClass_All`."
  default     = "PriceClass_All"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to all resources."
  default     = {}
}
